### PR TITLE
updated text model ( google drive needs to be addded)

### PR DESCRIPTION
**Pull request by ishmeetk**

### CODE REVIEW

**Comment by ishmeetk** [comment]
Formated according to ensemble

**Comment by amilkh** [comment]
1. please remove .DS_store from the commit
1. let's use the class structure from the original file: https://github.com/virufy/covid/blob/master/text/text_model.ipynb
it's better than using global functions from a software engineering perspective

**Comment by ishmeetk** [comment]
Juts look at text() class and lmk if that works. i will clean other stuff and make a final pull request.

**Comment by amilkh** [comment]
closing outdated PR, please reopen ifmy mistake

**Pull request closed without merging**
