### PR TITLE
Add new text model

### PR DESCRIPTION
**Pull request by ashah03**

### CODE REVIEW

**Comment by amilkh** [comment]
overall looks good!

few changes

1. remove commented out stuff, not really good programming practice
```
"""
import math
from datetime import datetime

import seaborn as sns
import matplotlib.pyplot as plt
"""
"""
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

"""
```

2. please match API in https://docs.google.com/document/d/1bfpwvUr78XzJxow6optf4OBUgW6rqziCdr5yL_rVVWc/edit

3. please have another developer (beginner) run this code on their machine to validate

**Comment by junmingguan** [comment]
The code runs fine on my machine.

**Comment by amilkh** [comment]
great! plz merge after the requsted changes above and also Jaclyn approves it!

**Comment by vivianross06** [comment]
worked on my computer

**Comment by amilkh** [comment]
awesome work! merged

**Pull request merged**
