### PR TITLE
Add the text model file with data preprocessing methods

### PR DESCRIPTION
**Pull request by cc-21**
**Summary of Changes**
Add the IPYNB file for the text model.

### CODE REVIEW

**Comment by amilkh** [comment]
looks good! want me to merge it?
will be good if we can have it to run on the /data folder so anyone can run it simply by clone the repoistory

**Comment by cc-21** [comment]
The link to the data is updated now.

**Comment by amilkh** [comment]
you can add a !wget or !git clone cell to get the data from github so that you can run it in the notebook

**Comment by amilkh** [comment]
saw you added `! wget --quiet https://github.com/virufy/covid/tree/master/data/labels.csv` this is perfect!

**Pull request merged**
